### ISSUE TITLE
Any way to allow passthrough of tap events?

### ISSUE THREAD

**Issue by jesper-bylund** [jerrybendy/react-touch-events#5]
I'm using with together with the <Link /> component from React Router and ReactTouchEvents seems to block it's use of the onClick. Has anyone tested these together and got them to work?

**Comment by jerrybendy** [comment]
A way to avoid passthrough bugs is only listen elements' tap event, but click event.

If your web app only support for mobile, you can use the new `disableClick` option to cancel bind click event for element. You can update your dependence to version 1.1.0 to use this option.

If you have better ideas to do so, please tell me. 😉

Thanks
